### ISSUE TITLE
Write documentation of our ADR process

### ISSUE THREAD

**Issue by shonfeder** [apalache-mc/apalache#1071]
Discussed in our strategy meeting today.

We'd like to clarify and codify our ADR process. Opening a PR documenting this will give us a space to work out a common understanding of the aims and what's expected.

The documentation should cover:

- What is the purpose of an ADR
- When should you write an ADR
- Who should write an ADR
- What template should be used when writing an ADR (i.e., what should be included)
- Who are they written for

**Comment by konnov** [comment]
Higher-order management issue :)
