### ISSUE TITLE
[FEATURE] Get coverage reports on black box integration tests

### ISSUE THREAD

**Issue by shonfeder** [apalache-mc/apalache#1266]
This would help us get a clearer sense of our coverage and perhaps spot dead code.

I'm not sure if this is feasible, but @konnov and I found some leads:

- https://stackoverflow.com/questions/16208539/measure-code-coverage-through-black-box-testing-in-java-web-application?rq=1
- https://blog.developer.atlassian.com/using-jacoco-a-code-coverage-tool-for-scala/

**Comment by konnov** [comment]
it did not look like code coverage was used by anyone
