### ISSUE TITLE
SBT build script should make it optional to retrieve version information from git

### ISSUE THREAD

**Issue by soareschen** [apalache-mc/apalache#1653]
The current [`build.sbt`](https://github.com/informalsystems/apalache/blob/b2b11ae6917ac2555608e38ff6a329a6131b8bf8/build.sbt#L187) relies on calling `git describe` to get the build version of the package. However the git information is not always available, especially when downloading the tarball directly from GitHub. The `git` command is also not always available, such as in the case of inside the default build environment in Nix.

This cause issue when packaging Apalache in Cosmos.nix. Currently as a workaround, I added a [patch on `build.sbt`](https://github.com/informalsystems/apalache/blob/b2b11ae6917ac2555608e38ff6a329a6131b8bf8/build.sbt#L187) to override the version with a hardcoded one. While this works, it is not very convenient.

A better solution is to modify `build.sbt` and make it such that getting version information from `git` becomes optional. If calling the git command failed, the build script should instead get the version information from elsewhere, such as from the [VERSION](https://github.com/informalsystems/apalache/blob/b2b11ae6917ac2555608e38ff6a329a6131b8bf8/VERSION) file.

**Comment by konnov** [comment]
I don't think it's relevant anymore
