### ISSUE TITLE
Automate linking in changelog 

### ISSUE THREAD

**Issue by shonfeder** [apalache-mc/apalache#1767]
Expands @konnov's request at https://github.com/informalsystems/apalache/issues/1538#issuecomment-1125714589

- Auto link issue numbers
- Auto link `@` mentions
- Auto link version numbers in headings to github diff range (just based on tags)
- Add the date alongside the release version

**Comment by konnov** [comment]
The main motivation was to automatically generate ICF reports in the future. Definitely not an issue!
