### ISSUE TITLE
Highlight modified values in counterexamples

### ISSUE THREAD

**Issue by p-offtermatt** [apalache-mc/apalache#1884]
## Is your feature request related to a problem? Please describe

It's sometimes hard to tell which variables are modified between states of the counterexample.

```(* Initial state *)
State0 ==
  __FalseLiveness_init = FALSE
    /\ __InLoop = FALSE
    /\ __saved___temporal_t_1 = FALSE
    /\ __saved_x = 0
    /\ __temporal_t_1 = FALSE
    /\ __temporal_t_1_unroll = FALSE
    /\ __temporal_t_1_unroll_prev = FALSE
    /\ x = 0

(* Transition 1 to State1 *)
State1 ==
  __FalseLiveness_init = FALSE
    /\ __InLoop = TRUE
    /\ __saved___temporal_t_1 = FALSE
    /\ __saved_x = 0
    /\ __temporal_t_1 = FALSE
    /\ __temporal_t_1_unroll = FALSE
    /\ __temporal_t_1_unroll_prev = FALSE
    /\ x = 1
```

## Describe the solution you'd like

There is some sort of indication that a variable changes between states of the counterexample,
like in the TLC toolbox. For example, comment MODIFIED after variables that changed.

```(* Initial state *)
State0 ==
  __FalseLiveness_init = FALSE
    /\ __InLoop = FALSE
    /\ __saved___temporal_t_1 = FALSE
    /\ __saved_x = 0
    /\ __temporal_t_1 = FALSE
    /\ __temporal_t_1_unroll = FALSE
    /\ __temporal_t_1_unroll_prev = FALSE
    /\ x = 0

(* Transition 1 to State1 *)
State1 ==
  __FalseLiveness_init = FALSE
    /\ __InLoop = TRUE  (* MODIFIED *)                                   
    /\ __saved___temporal_t_1 = FALSE
    /\ __saved_x = 0
    /\ __temporal_t_1 = FALSE
    /\ __temporal_t_1_unroll = FALSE
    /\ __temporal_t_1_unroll_prev = FALSE
    /\ x = 1 (* MODIFIED *)
```

## Describe alternatives you've considered

I've run a diff-checker on the text blocks for the states, but that's cumbersome.

Maybe the real solution is to use (or implement, if it doesn't exist) some visualizer
which anyways presents traces in a nicer format. Implementing this feature could, however,
be useful until such a visualizer exists.

**Comment by konnov** [comment]
I have found that copilot perfectly finds modified values in counterexamples
