### ISSUE TITLE
Data abstraction over integers

### ISSUE THREAD

**Issue by konnov** [apalache-mc/apalache#2171]
TLA+ has unbounded integers, which Apalache translates to SMT integers. We have seen examples where the actual set of integers is quite small. Nevertheless, z3 has to solve equations over LIA.

Consider the following (rather simple) example:

```tla
------ MODULE t -----
EXTENDS Integers

VARIABLE
  \* @type: Int;
  x,
  \* @type: Int;
  y

Init ==
  x = 0 /\ y = 0

Next ==
  \/ x < 2 /\ x' = x + 1 /\ UNCHANGED y
  \/ x > 0 /\ x' = x - 1 /\ UNCHANGED y
  \/ y < 2 /\ y' = y + 1 /\ UNCHANGED x
  \/ y > 0 /\ y' = y - 1 /\ UNCHANGED x

Inv ==
  x <= 2 /\ y <= 2
=====================
```

In the above example, it is clear that `x` and `y` range over `0..2`. However, it may be not clear to the SMT solver, and it will have to solve equations.

We can apply the data abstraction to replace `+` and `-` with `Inc` and `Dec`:

```tla
------ MODULE t2 -----
EXTENDS Integers

VARIABLE
  \* @type: Int;
  x,
  \* @type: Int;
  y

Inc(a) ==
    CASE a = 0 -> 1
      [] a = 1 -> 2
      [] a = 2 -> -1
      [] a = -1 -> -1

Dec(a) ==
    CASE a = 0 -> -1
      [] a = 1 -> 0
      [] a = 2 -> 1
      [] a = -1 -> -1

Init ==
  x = 0 /\ y = 0

Next ==
  \/ x /= 2 /\ x' = Inc(x) /\ UNCHANGED y
  \/ x /= 0 /\ x' = Dec(x) /\ UNCHANGED y
  \/ y /= 2 /\ y' = Inc(y) /\ UNCHANGED x
  \/ y /= 0 /\ y' = Dec(y) /\ UNCHANGED x

Inv ==
  (x = 0 \/ x = 1 \/ x = 2) /\ (y = 0 \/ y = 1 \/ y = 2)
=====================
```

This is a well-known data abstraction, e.g., described by Ken McMillan in [Verification of Infinite State Systems by Compositional Model Checking](https://link.springer.com/chapter/10.1007/3-540-48153-2_17).

It may gives us a significant boost in performance. For example, in one of our benchmarks, we got a 10x speedup by doing exactly that. It does not seem to be hard to automate this abstraction. We could do it as a purely preprocessing step.

Even in the above example, we get better running times:

```sh
$ apalache-mc check --length=100 --inv=Inv t.tla
# 159.155 s ± 14.394 s
$ apalache-mc check --length=100 --inv=Inv t2.tla
# 123.103 s ±  2.133 s
```

**Comment by thpani** [comment]
Since you're abstracting to a finite domain, I think you could even get away without any integers in the spec, which would allow Z3 to pick a more efficient theory solver?

**Comment by konnov** [comment]
Yep, though it looks when we are using integer literals, it is not the bottleneck. Essentially, integer literals are immediately translated into constants in Apalache.

**Comment by konnov** [comment]
It looks like `cvc5` has a bit-vector abstraction of integers. So it would be more meaningful to integrate `cvc5` and use its features rather than implementing this abstraction.
