### ISSUE TITLE
Decide the (short/mid-term) fate of Multicore

### ISSUE THREAD

**Issue by Kukovec** [apalache-mc/apalache#2645]
In service of multicore, an experiment initially conducted by @konnov , several classes (e.g. cahces) implement serialization features, which are redundant in the current implementation. We need to decide on the timeline/feasibility of multicore, since disregarding the serialization features would allow us to significantly simplify the architecture in the refactoring of these utility classes.

**Comment by konnov** [comment]
Serialization features may still be needed at some point, but multicore, as it was implemented in 2020, is not relevant
