### ISSUE TITLE
Fix the release pipeline

### ISSUE THREAD

**Issue by konnov** [apalache-mc/apalache#2951]
The last step did not work: https://github.com/apalache-mc/apalache/actions/runs/10434305251

**Comment by lemmy** [comment]
```
...
+ VERSION=0.45.1-SNAPSHOT
++ git show -s --format=%s HEAD
+ msg='Bump version to 0.45.1-SNAPSHOT'
+ [[ Bump version to 0.45.1-SNAPSHOT != \[\r\e\l\e\a\s\e\]\ \0\.\4\5\.\1\-\S\N\A\P\S\H\O\T ]]
+ echo 'error: HEAD commit must be a [release] commit'
+ echo 'found: Bump version to 0.45.1-SNAPSHOT'
+ exit 4
error: HEAD commit must be a [release] commit
found: Bump version to 0.45.1-SNAPSHOT
```

The error message suggests that the git commit message has to be amended to `[release] 0.45.1-SNAPSHOT`.

**Comment by konnov** [comment]
@thpani figured out that no other PR should land on main between `prepare-release` and `release`. This has worked.
