### ISSUE TITLE
[FEATURE] Automatically determine release increment in CI

### ISSUE THREAD

**Issue by shonfeder** [apalache-mc/apalache#559]
If we are willing to follow semver, we should be able to determine this automatically from the contents of `UNRELEASED.md` as follows:

- If it contains the heading `## Breaking changes`, increment the major version (not relevant until we graduate to 1.0.0).
- If it contains the heading `## Features`, increment the minor version
- Otherwise, it should only contain `## Bugfixes`, so increment the patch version

**Comment by konnov** [comment]
Irrelevant
